compass/urls.py
from django.conf.urls import patterns, include, url
from compass import views

urlpatterns = patterns('',
    url(r'^$', views.index),
    url(r'^enquiry/$', views.enquiry),
    url(r'^about/$', views.about),
    url(r'^service/$', views.services),
    url(r'^careers/$', views.career),
    url(r'^contact/$', views.message),
    url(r'^enquiry_success/$', views.e_success),
    url(r'^message_success/$', views.m_success),
    url(r'^vessel/$', views.vessel),
    url(r'^custom/$', views.custom),
    url(r'^transport/$', views.transport),
    url(r'^freight/$', views.freight),
    url(r'^picorrespondents/$', views.pi),
    url(r'^ship/$', views.ship),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', views.logout_page),
    url(r'^register/$', views.register),
    url(r'^register/success/$', views.register_success),
    url(r'^search/$', views.search, name='search'),
    url(r'^search/(?P<reference_no>\S+)/$', views.status),
    
)

myproject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myproject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('compass.urls')),
)

compass/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
# Create your models here.

class Enquiry(models.Model):

    vessel_agency = "Vessel Agency"
    customs_clearance = "Customs Clearance"
    trasportation = "Transportation"
    freight_forwarding = "Freight Forwarding"
    ship_chandling = "Ship Chandling"
    p_i_correspondents = "P & I Correspondents"
    enquiry_choices = ((vessel_agency, 'Vessel Agency'),
     (customs_clearance , "Customs Clearance"),
    (trasportation , "Transportation"),
     (freight_forwarding , "Freight Forwarding"),
     (ship_chandling , "Ship Chandling"),
     (p_i_correspondents , "P & I Correspondents"))
    
   
    services = models.CharField(max_length=40, choices=enquiry_choices)
    full_name = models.CharField(max_length=30)
    organisation = models.CharField(max_length=40)
    designation = models.CharField(max_length=40)
    contact_number = models.CharField(max_length=55)
    email = models.EmailField(max_length=50)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=80)
    enquiry = models.CharField(max_length=255, null=True, blank=True)
    def __unicode__(self):
        return self.full_name

class EnquiryAdmin(admin.ModelAdmin):
    list_display = ['services', 'full_name', 'organisation', 'designation', 'contact_number', 'email', 'city', 'country', 'enquiry']


class Message(models.Model):
    name = models.CharField(max_length=40, null=True, blank=True)
    email = models.CharField(max_length=40, null=True, blank=True)
    phone = models.CharField(max_length=40, null=True, blank=True)
    comment = models.TextField(null=True, blank=True)

class Track(models.Model):
	
   dispatched = "Dispatched"
   pending = "Pending"
   out_of_delivery = "Out of Delivery"
   delivered = "Delivered"
   track_choices=((dispatched, "Dispatched"),
		(pending, "Pending"),
		(out_of_delivery,"Out of Delivery"),
		(delivered, "Delivered"))
   reference_no = models.CharField(max_length=100)
   from_location = models.CharField(max_length=40)
   to_location = models.CharField(max_length=40)
   type = models.CharField(max_length=40)
   date = models.DateField()
   status = models.CharField(max_length=40, choices=track_choices)
   no_of_pieces = models.IntegerField(null=True, blank=True)
   def __unicode__(self):
	
        return self.reference_no
class CurrentStatus(models.Model):
    dispatched = "Dispatched"
    pending = "Pending"
    out_of_delivery = "Out of Delivery"
    delivered = "Delivered"
    track_choices=((dispatched, "Dispatched"),
		(pending, "Pending"),
		(out_of_delivery,"Out of Delivery"),
		(delivered, "Delivered"))

    reference_no = models.ForeignKey(Track)
    currernt_date = models.DateField()
    current_from_location = models.CharField(max_length=100)
    current_to_location = models.CharField(max_length=100)
    status = models.CharField(max_length=40, choices=track_choices)
    def __unicode__(self):
	return self.status

compass/forms.py
from django import forms

from compass.models import *

class RegistrationForm(forms.Form):
    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=("User Name"), error_messages={ 'invalid': ("This value must contain only letters, numbers and underscores.") })
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=("Email address"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=("Password (again)"))


    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(("The username already exists. Please try another one."))

    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(("The two password fields did not match."))
        return self.cleaned_data

class EnquiryForm(forms.ModelForm):

    class Meta:

        model = Enquiry
	fields = '__all__'

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

templates/contact.html
<!DOCTYPE html>
<html lang="en">


<head>
	<meta charset="UTF-8">
	<title>Compass-Shipping</title>
	<!-- viewport meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- styles -->
	<!-- helpers -->
	<link rel="stylesheet" href="/static/plugins-ship/bootstrap/css/bootstrap.min.css">
	<!-- fontawesome css -->
	<link rel="stylesheet" href="/static/plugins-ship/font-awesome/css/font-awesome.min.css">
	<!-- strock gap icons -->
	<link rel="stylesheet" href="/static/plugins-ship/Stroke-Gap-Icons-Webfont/style.css">
	<!-- revolution slider css -->
	<link rel="stylesheet" href="/static/plugins-ship/revolution/css/settings.css">
	<link rel="stylesheet" href="/static/plugins-ship/revolution/css/layers.css">
	<link rel="stylesheet" href="/static/plugins-ship/revolution/css/navigation.css">
	<!-- flaticon css -->
	<link rel="stylesheet" href="/static/plugins-ship/flaticon/flaticon.css">
	<!-- jQuery ui css -->
	<link href="/static/plugins-ship/jquery-ui-1.11.4/jquery-ui.css" rel="stylesheet">
	<!-- owl carousel css -->
	<link rel="stylesheet" href="/static/plugins-ship/owl.carousel-2/assets/owl.carousel.css">
	<link rel="stylesheet" href="/static/plugins-ship/owl.carousel-2/assets/owl.theme.default.min.css">
	<!-- animate css -->
	<link rel="stylesheet" href="/static/plugins-ship/animate.min.css">
	<!-- fancybox -->
	<link rel="stylesheet" href="/static/plugins-ship/fancyapps-fancyBox/source/jquery.fancybox.css">



	<!-- master stylesheet -->
	<link rel="stylesheet" href="/static/css-ship/style.css">
	<!-- responsive stylesheet -->
	<link rel="stylesheet" href="/static/css-ship/responsive.css">




</head>
<body>

<!-- Start header -->
<header id="header" class="stricky">
	<div class="thm-container clearfix">
		<div class="logo pull-left">
			<a href="/">
				<img src="/static/images-ship/logo.png" style="width:80%; height:60%;" alt="">
			</a>
		</div>
		
	</div>
</header>
<!-- End header  -->

<!-- Start mainmenu -->
<nav class="main-menu-wrapper stricky">
	<div class="thm-container menu-gradient ">
		<div class="clearfix">
			<div class="nav-holder pull-left">
				<div class="nav-header">
					<button><i class="fa fa-bars"></i></button>
				</div>
				<div class="nav-footer">
					<ul class="nav">
						<li>
					<a href="/">Home</a>
					
				</li>
						<li>
							<a href="/about/">about us</a>
							
						</li>
						<li>
							<a href="/service/">Services</a>
							
						</li>
						<li>
							<a href="/careers/">Careers</a>
							
						</li>
						<li>
							<a href="/enquiry/">Enquiry</a>
							
						</li>
						
						<li><a href="/contact/">contact us</a></li>
						<li><form method="get" action="/search/" class="search-box-holder">
						<div class="search-box">
						<div class="form">
						<input type="text" style="width:250px; height:50px;" name="q" placeholder="&nbsp;&nbsp;&nbsp;Track Your Shipment">
						<button type="submit"><span>GO</span></button>
						</div>
					</div>
				</form></li>
					</ul>
				</div>
			</div>
							
				
		
		</div>
	</div>
</nav>
<!-- End mainmenu -->


<section class="inner-banner">
	<div class="thm-container">
		<h2>Contact Us</h2>
		<ul class="breadcumb">
			<li><a href="/"><i class="fa fa-home"></i> Home</a></li>
			<li><span>Contact Us</span></li>
		</ul>
	</div>
</section>


<section class="sec-padding">
	<div class="thm-container">
		<div class="sec-title">
			<h2><span>Get in touch</span></h2>
			<p>Fill up below instant messaging programs.</p>

		</div>

		<div class="row">
			<div class="col-md-7 col-sm-6 col-xs-12 pull-left">
				{% if done %}
        <p> Your message is successfully. Will get back to you as soon as possible.. Thanks </p>
					{% else %}
				<form id="my-contact-form" method="post" class="form-horizontal"  role="form">
                    {% csrf_token %}
                    <fieldset>
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input id="id_name" name="name" type="text" value="" required="required" pattern="[A-Za-z0-9]{1,}" class="form-control form_input" placeholder="Name">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input id="id_email" name="email" type="email" value="" required="required" class="form-control form_input" placeholder="Email">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input id="id_phone" name="phone" type="text" pattern="[0-9]{10}"  class="form-control form_input" placeholder="Phone">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <textarea class="form-control form_textarea" required="required" id="comment" name="comment" placeholder="Enter your message" rows="7"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                            </div>
                        </div>
                    </fieldset>
                </form>

{% endif %}			
</div>

			<div class="col-md-4 col-sm-6 col-xs-12 pull-right">
				<div class="contact-info">
					<ul>
						<li>
							<div class="icon-box">
								<i class="icon icon-Pointer"></i>
							</div>
							<div class="content">
								<p>P.O BOX: 324 <br> POSTAL CODE: 318 <br>	SOHAR, AL FALAJ<br>SULTANATE OF OMAN</p>
								
							</div>
						</li>
						<li>
							<div class="icon-box">
								<i class="icon icon-Plaine"></i>
							</div>
							<div class="content">
								<p>operation.manager@compass-ship.com <br>general.manager@compass-ship.com</p>
							</div>
						</li>
						<li>
							<div class="icon-box">
								<i class="icon icon-Phone2"></i>
							</div>
							<div class="content">
								<p>00968 9142 3785<br>00968  9293 3304</p>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
		
	</div>
</section>
 


<section class="footer-top">
	<div class="thm-container">
		<div class="row">
			<div class="col-md-12">
				<div class="col-md-6">
					<h3>Logistic and cargo</h3>
					<p style="color:black;">Contact us now to get quote for all your global <br>shipping and cargo need.</p>
				</div>
				<div class="col-md-6">
					<a class="thm-btn" href="/contact/">Contact Us <i class="fa fa-arrow-circle-right"></i></a>
				</div>
			</div>
		</div>
	</div>
</section> 


<footer id="footer" class="sec-padding">
 <div class="thm-container">
  <div class="row">
   <div class="col-md-3 col-sm-6 footer-widget">
    <div class="about-widget">
     <a href="/"><img src="/static/images-ship/footer-logo1.png" alt="Awesome Image"/></a>
     
     <ul class="social">
      <li><a href="/facebook"><i class="fa fa-facebook"></i></a></li>
      <li><a href="/twitter"><i class="fa fa-twitter"></i></a></li>
      <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
      <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
     </ul>
    </div>
   </div>
   <div class="col-md-3 col-sm-6 footer-widget">
    <div class="pl-30">
     <div class="title">
      <h3><span>Our Services</span></h3>
     </div>
     <ul class="link-list">
      <li><a href="/vessel/">Vessel Agency</a></li>
      <li><a href="/custom/">Customs Clearance</a></li>
      <li><a href="/transport/">Transportation</a></li>
      <li><a href="/freight/">Freight Forwarding</a></li>
      <li><a href="/ship/">Ship Chandling</a></li>
      <li><a href="/picorrespondents/">P & I Correspondents</a></li>
     </ul>
    </div>
   </div>
   <div class="col-md-2 col-sm-6 footer-widget">
    <div class="title">
     <h3><span>Quick Links</span></h3>
    </div>
    <ul class="link-list">
     <li><a href="/">Home</a></li>
     <li><a href="/about/">About Us</a></li>
     <li><a href="/service/">Services</a></li>
     <li><a href="/careers/">Careers</a></li>
     <li><a href="/enquiry/">Enquiry</a></li>
     <li><a href="/contact/">Contact Us</a></li>
    </ul>
   </div>
   <div class="col-md-4 col-sm-6 footer-widget">
    <div class="title">
     <h3><span>Quick Contact</span></h3>
    </div>
    <ul class="contact-infos">
     <li>
      <div class="icon-box">
       <i class="fa fa-map-marker"></i>
      </div>
      <div class="text-box">
       <p>P.O BOX: 324 <br> POSTAL CODE: 318 <br> SOHAR, AL FALAJ<br>SULTANATE OF OMAN</p>
      </div>
     </li>
     <li>
      <div class="icon-box">
       <i class="fa fa-phone"></i>
      </div>
      <div class="text-box">
       <p>00968 9142 3785<br>00968  9293 3304</p>
      </div>
     </li>
     <li>
      <div class="icon-box">
       <i class="fa fa-envelope-o"></i>
      </div>
      <div class="text-box">
       <p>operation.manager@compass-ship.com <br>general.manager@compass-ship.com</p>
      </div>
     </li>
     <li>
      
     </li>
    </ul>
   </div>
  </div>
 </div>
</footer>

<section class="bottom-bar">
	<div class="thm-container clearfix">
		<div class="pull-left">
			<p>Copyright © Compass-Shipping 2016. All rights reserved.</p>
		</div>
		<div class="pull-right">
			<p>Created by: Delevere</p>
		</div>
	</div>
</section>

<!-- jQuery js -->
<script src="/static/plugins-ship/jquery/jquery-1.11.3.min.js"></script>
<!-- bootstrap js -->
<script src="/static/plugins-ship/bootstrap/js/bootstrap.min.js"></script>
<!-- jQuery ui js -->
<script src="/static/plugins-ship/jquery-ui-1.11.4/jquery-ui.js"></script>
<!-- owl carousel js -->
<script src="/static/plugins-ship/owl.carousel-2/owl.carousel.min.js"></script>
<!-- jQuery appear -->
<script src="/static/plugins-ship/jquery-appear/jquery.appear.js"></script>
<!-- jQuery countTo -->
<script src="/static/plugins-ship/jquery-countTo/jquery.countTo.js"></script>
<!-- jQuery validation -->
<script src="/static/plugins-ship/jquery-validation/dist/jquery.validate.min.js"></script>
<!-- gmap.js helper -->
<script src="http://maps.google.com/maps/api/js"></script>
<!-- gmap.js -->
<script src="/static/plugins-ship/gmap.js"></script>
<!-- mixit up -->
<script src="/static/plugins-ship/jquery.mixitup.min.js"></script>

<!-- revolution slider js -->
<script src="/static/plugins-ship/revolution/js/jquery.themepunch.tools.min.js"></script>
<script src="/static/plugins-ship/revolution/js/jquery.themepunch.revolution.min.js"></script>
<script src="/static/plugins-ship/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script src="/static/plugins-ship/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
<script src="/static/plugins-ship/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
<script src="/static/plugins-ship/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script src="/static/plugins-ship/revolution/js/extensions/revolution.extension.migration.min.js"></script>
<script src="/static/plugins-ship/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script src="/static/plugins-ship/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
<script src="/static/plugins-ship/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
<script src="/static/plugins-ship/revolution/js/extensions/revolution.extension.video.min.js"></script>

<!-- fancy box -->
<script src="/static/plugins-ship/fancyapps-fancyBox/source/jquery.fancybox.pack.js"></script>
<!-- type script -->
<script src="/static/plugins-ship/typed.js-master/dist/typed.min.js"></script>

<!-- theme custom js  -->
<script src="/static/js-ship/main.js"></script>



</body>

<!-- Mirrored from designarc.in/logis-cargo/contact.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 14 Apr 2016 11:41:21 GMT -->
</html>